apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client
  namespace: trading
  labels:
    app: cockroachdb-client
spec:
  containers:
  - name: client
    image: cockroachdb/cockroach:v23.2.0
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600000"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  restartPolicy: Always
